const express = require("express")
const {requestLogger,urlLogger} = require("./middlewares")
const app = express()
const cors = require('cors')
const bodyParser = require("body-parser")
app.use(bodyParser.json())
app.use(cors())
app.use(requestLogger)
app.use(urlLogger)
app.use(bodyParser.urlencoded({ extended: false }))
const configRoutes = require("./routes")
configRoutes(app)
app.listen(3000, ()=>{
console.log("We have a server up and running perfectly fine")
})